### ISSUE TITLE
Help with detail query

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/peas#1]
What is wrong with the following query?
Endpoint $will-be-given-shortly

{
 "loggingLevel": 0,
 "queryID": "73997588",
 "documentBadge": [
   {
     "uri": "http:\/\/www.mendeley.com\/research\/geothermobarometry-geochronology-mineral-assemblages-orthogneisses-related-metapelites-spessart-crys",
     "provider": "Mendeley",
     "id:": "8dfb2519-7d1f-3cb9-921d-47f88e652ea3"
   }
 ],
 "origin": {
   "clientType": "Swift-Test-Client",
   "clientVersion": "0.21",
   "module": "OS X Prototype",
   "userID": "PDPS-WS2015"
 }

Error report 
<html><head><title>Apache Tomcat/7.0.47 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException
    eu.eexcess.insa.peas.QueryEngine.processRegularQuery(QueryEngine.java:115)
    eu.eexcess.insa.peas.QueryEngine.processQuery(QueryEngine.java:103)
    eu.eexcess.insa.Issuer.getDetails(Issuer.java:144)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    java.lang.reflect.Method.invoke(Unknown Source)
    com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)

**Comment by hziak** [comment]
bracket is missing at the end } but i don't know if thats a copy past error

in the document badge: 
"id:": "8dfb2519-7d1f-3cb9-921d-47f88e652ea3"
should be "id":"..." i guess

but no idea if thats the problem

**Comment by ThomasCerq** [comment]
There are several problems. The first one is that a "}" is missing at the end of the query. It should be: 
{
    "loggingLevel": 0,
    "queryID": "73997588",
    "documentBadge": [{
        "uri": "http:\/\/www.mendeley.com\/research\/geothermobarometry-geochronology-mineral-assemblages-orthogneisses-related-metapelites-spessart-crys",
        "provider": "Mendeley",
        "id:": "8dfb2519-7d1f-3cb9-921d-47f88e652ea3"
    }],
    "origin": {
        "clientType": "Swift-Test-Client",
        "clientVersion": "0.21",
        "module": "OS X Prototype",
        "userID": "PDPS-WS2015"
    }
}

I'm not sure I handle correctly the loggingLevel attribute on the PP. I need to check it... 

Last, I tried to directly send the following query to the FR and I got an error because of the "id" attribute. I'm not sure it's the expected behaviour... 
{
    "documentBadge": [{
        "uri": "http:\/\/www.mendeley.com\/research\/geothermobarometry-geochronology-mineral-assemblages-orthogneisses-related-metapelites-spessart-crys",
        "provider": "Mendeley",
        "id:": "8dfb2519-7d1f-3cb9-921d-47f88e652ea3"
    }]
}

I work on it right now and let you know when the PP works correctly.

**Comment by pstoehr** [comment]
The "missing" curly bracket comes in fact from a copy-and-paste error. 
The id was taken from a result that was generate by a query to the Privacy Proxy Services.

**Comment by pstoehr** [comment]
Sorry, I forgot to provide the endpoint of the query: 
https://eexcess-dev.joanneum.at/eexcess-privacy-proxy-issuer-1.0-SNAPSHOT/issuer/getDetails

**Comment by ThomasCerq** [comment]
Can you please try with this endpoint: https://eexcess-dev.joanneum.at/eexcess-privacy-proxy-issuer-1.0-DEV-SNAPSHOT/issuer/getDetails ?
I use this endpoint for testing purposes. If the problem is fixed, I'll update the one you're using.

**Comment by pstoehr** [comment]
Works as expected!

Thanks!

{
  "documentBadge": [
    {
      "provider": "Mendeley",
      "id": "8dfb2519-7d1f-3cb9-921d-47f88e652ea3",
      "detail": {
        "eexcessProxy": {
          "dccreator": [
            "A Dombrowski",
            {
              "content": "A Dombrowski"
            },
            "M Okrusch",
            {
              "content": "M Okrusch"
            },
            "F Henjeskunst",
            {
              "content": "F Henjeskunst"
            }
          ],
          "dcidentifier": "8dfb2519-7d1f-3cb9-921d-47f88e652ea3",
          "dctermsdate": "1994",
          "dcdescription": "Granitic orthogneisses of the Rotgneiss and the Haibach Gneiss type in the Spessart Crystalline Complex (SCC), an important constituent of the Mid-German Crystalline Rise, contain the amphibolite-facies assemblage quartz + K-feldspar + oligoclase + muscovite + biotite +\/- garnet. From the combined application of the garnet-biotite geothermometer, the muscovite-biotite geothermobarometer and the phengite geobarometer to this assemblage, peak metamorphic temperatures of 600-650-degrees-C and pressures of 4-7 kbar are deduced, consistent with earlier estimates based on mineral parageneses in staurolite-bearing metapelites and metabasites in the SCC. From an intercalated metapelitic schist of the Schweinheim Formation temperatures of 590-620-degrees-C and pressures of 6-8 kbar are estimated possibly indicating that the prograde metamorphic evolution passed through conditions with slightly higher P\/T ratios. Some of the muscovites of the Rotgneiss and the Haibach gneiss, especially cores of zoned muscovite flakes, are characterized by higher Si contents, up to 6.6 per formula unit, indicating still lower temperatures and\/or higher pressures. Radiometric dating of mica concentrates from the Haibach gneiss yielded conventional K-Ar dates of 323-325 +\/- 2 Ma and 315-323 +\/- 2 Ma for muscovite and biotite, respectively, and concordant Rb-Sr whole rock-muscovite dates of 323 and 326 +\/- 7 Ma. A concordant Ar-Ar plateau date of 324 +\/- 3 Ma was recorded on one muscovite from the Haibach gneiss. These model ages agree well with previously published K-Ar dates on hornblende, biotite and muscovite from different rock types in the SCC. They record a short period of rapid uplift following deformation and amphibolite-facies metamorphism near the Visean\/Namurian boundary. Our results suggest that, during the Variscan orogenesis, the SCC underwent a clockwise P-T path.",
          "dctitle": "Geothermobarometry and Geochronology on Mineral Assemblages of Orthogneisses and Related Metapelites of the Spessart Crystalline Complex, Nw Bavaria, Germany",
          "edmeuropeanaProxy": "false"
        }
      },
      "uri": "http:\/\/www.mendeley.com\/research\/geothermobarometry-geochronology-mineral-assemblages-orthogneisses-related-metapelites-spessart-crys"
    }
  ],
  "queryID": "73997588"
}

**Comment by chseifert** [comment]
Thanks, guys!
