### ISSUE TITLE
correct syntax

### ISSUE THREAD

**Issue by schloett** [EEXCESS/peas#2]
Please correct the syntax for object definitions. 
It should be:
var someVar = {
    someFunction:function(parameter){
        // do something
    }
}
instead of:
var someVar = {
    someFunction(parameter){
        // do something
    }
}
Google's Chrome seems to be tolerant and there it works fine, just stumbled across this issue while using Opera, which throws errors.
Occurrences:
peas_indist.js - lines 48 & 57
peas_adapt.js - line 18
util.js - lines 21 & 36

**Comment by ThomasCerq** [comment]
I applied the correction to all the instances in peas_indist.js, peas_adapt.js and util.js.
