### ISSUE TITLE
Allow to turn off query obfuscation.

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/peas#3]
Currently, query obfuscation options are low, medium, high. I would like to turn it off completely. Maybe that is already the case with choosing low, but i do not know. So either change the description or add an OFF option. Thanks!

**Comment by schloett** [comment]
c.f. https://github.com/EEXCESS/chrome-extension/issues/54

**Comment by ThomasCerq** [comment]
I made the modifications. Now the 3 options are: None, Low and High. The updated code is pushed in the develop branch. 
Can you close the issue if it's good for you, or let me know what to modify?
